# //MOSTRAR TIPO PRODUCTO
# curl http://localhost:1337/tipoProducto/1

# //MOSTRAR TODOS LOS TIPOS DE PRODUCTOS
# curl http://localhost:1337/tipoProducto

//AGREGAR TIPO PRODUCTO
# curl -X POST \
#   -H "Content-Type: application/json" \
#   -d '{
#     "descripcionProducto": "Escalera Gigante"
# }' \
#   http://localhost:1337/tipoProducto

//UPDATEAR TIPO PRODUCTO
#   curl -X PATCH \
#   -H "Content-Type: application/json" \
#   -d '{
#     "IDVendedor": 4,
#     "nombreVendedor": "Steve Austin"
# }' \
#   http://localhost:1337/vendedor/4

# //ELIMINAR TIPO PRODUCTO
# curl -X DELETE http://localhost:1337/tipoProducto/:id
