# //Mostrar producto
# curl http://localhost:1337/producto/1/1/1

# //Mostrar todos los productos
# curl http://localhost:1337/producto

//AGREGAR producto
# curl -X POST -H "Content-Type: application/json" -d '{
#   "IDVendedor": 4,
#   "IDComprador": 3,
#   "IDTipoProducto": 4,
#   "precioCompra": 15900
# }' http://localhost:1337/producto

//UPDATE producto
# curl -X PATCH -H "Content-Type: application/json" -d '{
#   "precioCompra": 54000
# }' http://localhost:1337/producto/:numeroVendedor/:idComprador/:idTipoProducto

# //ELIMINAR producto
# curl -X DELETE http://localhost:1337/producto/:numeroVendedor/:idComprador/:idTipoProducto
